export const ActionTypes = {
  // error handling action types
  CLEAR_ERRORS: "CLEAR_ERRORS",
  RETURN_ERRORS: "RETURN_ERRORS",
  // loaders
  ACTION_SHOW_LOADER: "ACTION_SHOW_LOADER",
  //  flights
  GET_FLIGHTS_SUCCESS: "GET_FLIGHTS_SUCCESS",
  GET_FLIGHTS_FAIL: "GET_FLIGHTS_FAIL",
  CLEAR_FLIGHTS: "CLEAR_FLIGHTS",
};
